-- Combo lab: discovers Dudley combos by brute force using save states.
--
-- For each starter (st.HK, cr.HK, f.MK, ...) at midscreen and in the corner it:
--   1. places both characters, lands the starter, saves a state on the hit
--   2. tries every follow-up in moves.LAB_STEPS at every timing in LAB_DELAYS
--   3. keeps the most damaging routes that are true combos (the opponent never
--      became free) and extends them again, beam-search style, up to MAX_DEPTH
-- The best route per meter budget is written to saved/dudley_combos.lua and
-- the fighting AI uses it from then on. Results are per opponent character.
--
-- The fighting AI runs this by itself for every character it has not studied yet.
local gamestate = require("src.gamestate")
local inputs = require("src.control.inputs")
local framedata = require("src.data.framedata")
local settings = require("src.settings")
local utils = require("src.data.utils")
local write_memory = require("src.control.write_memory")
local moves = require("src.ai.dudley_moves")
local E = require("src.ai.route_exec")

local L = {
   BEAM = 3,
   MAX_DEPTH = 4,
   TRIAL_FRAMES = 300,
   results_path = "saved/dudley_combos.lua",
   root_state_path = "data/sfiii3nr1/savestates/dudley_lab_root.fs",
}

local lab = nil
local root_state = nil

---------------------------------------------------------------- results file
local function serialize(v, indent)
   indent = indent or ""
   if type(v) == "table" then
      local out = { "{\n" }
      for k, val in pairs(v) do
         local key = type(k) == "number" and ("[" .. k .. "]") or ("[%q]"):format(k)
         out[#out + 1] = indent .. "  " .. key .. " = " .. serialize(val, indent .. "  ") .. ",\n"
      end
      out[#out + 1] = indent .. "}"
      return table.concat(out)
   elseif type(v) == "string" then
      return ("%q"):format(v)
   end
   return tostring(v)
end

function L.load_results()
   local f = io.open(L.results_path, "r")
   if not f then return {} end
   local chunk = loadstring and loadstring(f:read("*a")) or load(f:read("*a"))
   f:close()
   local ok, res = pcall(chunk or function() return {} end)
   return ok and res or {}
end

function L.save_results(results)
   local f = io.open(L.results_path, "w")
   if not f then return end
   f:write("-- Generated by the Dudley combo lab. Delete to start over.\nreturn " .. serialize(results) .. "\n")
   f:close()
end

---------------------------------------------------------------- helpers
local function players(ai)
   return gamestate.player_objects[ai.player_id], gamestate.player_objects[3 - ai.player_id]
end

local function budget_of(chain)
   local ex, sup = E.cost(chain)
   if sup > 0 then return "super" elseif ex > 0 then return "ex" end
   return "meterless"
end

local function place(me, opp, pos, gap)
   local left, right = utils.get_stage_limits(gamestate.stage, opp.char_str)
   local ox = pos == "corner" and left + 4 or math.floor((left + right) / 2)
   write_memory.write_pos_x(opp, ox)
   write_memory.write_pos_x(me, ox + gap)
   memory.writebyte(opp.addresses.life, 160)
end

local function all_candidates(prefix)
   local list = {}
   for _, step in ipairs(moves.LAB_STEPS) do
      for _, delay in ipairs(moves.LAB_DELAYS) do
         local chain = {}
         for i, el in ipairs(prefix) do chain[i] = el end
         chain[#chain + 1] = { step = step.name, delay = delay }
         list[#list + 1] = chain
      end
   end
   return list
end

---------------------------------------------------------------- state machine
function L.start(ai)
   local me, opp = players(ai)
   local t = settings.training
   t.meter_mode, t.stun_mode, t.life_mode, t.infinite_time = 5, 5, 1, true  -- infinite meter, no stun
   t.blocking_mode = 1
   root_state = root_state or savestate.create(L.root_state_path)
   lab = { roots = {}, r = 0, results = L.load_results(), opp_char = opp.char_str, log = {} }
   for _, starter in ipairs(moves.LAB_STARTERS) do
      for _, pos in ipairs({ "mid", "corner" }) do lab.roots[#lab.roots + 1] = { starter = starter, pos = pos } end
   end
   lab.results[lab.opp_char] = lab.results[lab.opp_char] or {}
   emu.speedmode("turbo")
   L.next_root()
end

function L.next_root()
   lab.r = lab.r + 1
   local root = lab.roots[lab.r]
   if not root then return L.finish() end
   lab.root = root
   lab.phase = "place"
   lab.tries = 0
   lab.gap = math.max(40, (framedata.get_hitbox_max_range_by_name("dudley", root.starter) or 60) + 10)
end

function L.finish()
   lab.results[lab.opp_char]._complete = true
   L.save_results(lab.results)
   emu.speedmode("normal")
   lab.phase = "done"
   print("Dudley combo lab finished vs " .. lab.opp_char .. ". Results in " .. L.results_path)
end

local function begin_depth(prefixes)
   lab.depth = (lab.depth or 0) + 1
   lab.queue = {}
   for _, p in ipairs(prefixes) do
      for _, c in ipairs(all_candidates(p)) do lab.queue[#lab.queue + 1] = c end
   end
   lab.depth_results = {}
   lab.phase = "trial_load"
end

local function record(chain, dmg, complete)
   local key = lab.root.starter .. "_" .. lab.root.pos
   local bucket = budget_of(chain)
   local entry = lab.results[lab.opp_char][key] or {}
   lab.results[lab.opp_char][key] = entry
   if dmg > 0 and (not entry[bucket] or dmg > entry[bucket].damage) then
      entry[bucket] = { damage = dmg, chain = chain, text = E.describe(chain) }
      print(("  %s %s [%s] %d dmg: %s"):format(lab.opp_char, key, bucket, dmg, E.describe(chain)))
   end
   if complete then lab.depth_results[#lab.depth_results + 1] = { chain = chain, dmg = dmg } end
end

function L.update(ai)
   if not lab or lab.phase == "done" then return lab ~= nil end
   if not gamestate.is_in_match_playable then return true end
   local me, opp = players(ai)
   local frame = gamestate.frame_number

   if lab.phase == "place" then
      place(me, opp, lab.root.pos, lab.gap)
      lab.wait_until = frame + 20
      lab.phase = "starter"
   elseif lab.phase == "starter" then
      if frame >= lab.wait_until and me.is_idle and opp.is_idle then
         inputs.queue_input_sequence(me, moves.S[lab.root.starter], 0, true)
         lab.hit_deadline = frame + 40
         lab.phase = "starter_hit"
      end
   elseif lab.phase == "starter_hit" then
      if opp.has_just_been_hit then
         savestate.save(root_state)
         lab.life0 = opp.life
         lab.depth = 0
         begin_depth({ {} })
      elseif frame > lab.hit_deadline then
         lab.tries = lab.tries + 1
         lab.gap = lab.gap - 10
         if lab.tries > 5 or lab.gap < 20 then L.next_root() else lab.phase = "place" end
      end
   elseif lab.phase == "trial_load" then
      lab.chain = table.remove(lab.queue, 1)
      if not lab.chain then
         -- depth finished: keep the best complete routes and go deeper
         table.sort(lab.depth_results, function(a, b) return a.dmg > b.dmg end)
         local keep = {}
         for i = 1, math.min(L.BEAM, #lab.depth_results) do keep[i] = lab.depth_results[i].chain end
         if #keep == 0 or lab.depth >= L.MAX_DEPTH then
            L.save_results(lab.results)
            return L.next_root() or true
         end
         begin_depth(keep)
         return true
      end
      Load_State_Caller = "dudley_lab"
      savestate.load(root_state)
      lab.phase = "trial_start"
   elseif lab.phase == "trial_start" then
      lab.ex = E.new(lab.chain)
      lab.trial_end = frame + L.TRIAL_FRAMES
      lab.min_life = opp.life
      lab.result = nil
      lab.phase = "trial_run"
   elseif lab.phase == "trial_run" then
      if opp.is_idle or opp.is_blocking then
         -- opponent is free: the combo is over
         record(lab.chain, lab.life0 - lab.min_life, lab.result == "done")
         lab.phase = "trial_load"
         return true
      end
      lab.min_life = math.min(lab.min_life, opp.life)
      if not lab.result or lab.result == "running" then
         lab.result = E.update(lab.ex, me, opp)
         if lab.result == "failed" then
            record(lab.chain, lab.life0 - lab.min_life, false)
            lab.phase = "trial_load"
         end
      end
      if frame > lab.trial_end then
         record(lab.chain, lab.life0 - lab.min_life, lab.result == "done")
         lab.phase = "trial_load"
      end
   end

   gui.text(8, 30, ("COMBO LAB vs %s  %d/%d %s %s  depth %d  queue %d"):format(
      lab.opp_char, lab.r, #lab.roots, lab.root and lab.root.starter or "", lab.root and lab.root.pos or "",
      lab.depth or 0, lab.queue and #lab.queue or 0))
   return true
end

function L.is_running() return lab ~= nil and lab.phase ~= "done" end

return L
